link to orocos_kdl explicitly
This fixes the following error:

Linking CXX executable $HOME/ros/hydro/wet-ws/devel/lib/robot_state_publisher/state_publisher
/usr/bin/ld: CMakeFiles/robot_state_publisher.dir/src/joint_state_listener.cpp.o: undefined reference to symbol '_ZN3KDL7SegmentD1Ev'
$HOME/ros/hydro/wet/lib/liborocos-kdl.so.1.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status